#!/bin/bash

# Update and deploy reports.

SOURCE_DIR=~/src/cspace-deployment
SERVICES_DIR=$SOURCE_DIR/services
#DEPLOYMENT_NAME=`csname`
REPORT_DIR_SRC=$SOURCE_DIR/services/report/3rdparty/jasper-cs-report/src/main/resources
REPORT_DIR_DST=$CATALINA_HOME/cspace/reports
IMAGE_DEST_DIR=$CATALINA_HOME/webapps/reports/images
LIB_DEST_DIR=$CATALINA_HOME/lib

#cd $SERVICES_DIR

echo "Deploying reports..."

cp $REPORT_DIR_SRC/*.jrxml $REPORT_DIR_DST

if ls $REPORT_DIR_DST/*.jasper &> /dev/null; then
	rm $REPORT_DIR_DST/*.jasper
fi

IMAGE_SRC_DIR=$REPORT_DIR_SRC/images

if ls $IMAGE_SRC_DIR/* &> /dev/null; then
	mkdir -p $IMAGE_DEST_DIR
	cp $IMAGE_SRC_DIR/* $IMAGE_DEST_DIR
fi

LIB_SRC_DIR=$REPORT_DIR_SRC/images/lib

if ls $LIB_SRC_DIR/* &> /dev/null; then
	mkdir -p $LIB_DEST_DIR
	cp $LIB_SRC_DIR/* $LIB_DEST_DIR
fi

echo "Reports for $DEPLOYMENT_NAME deployed"
