#!/bin/bash

# Print the pid of the CollectionSpace tomcat service.

DEPLOYMENT_NAME=`csname`

/bin/systemctl show -p MainPID `csservname` 2>/dev/null | /bin/cut -d= -f2
#pgrep -fn -u $USER "java .* -Dcatalina.base=/var/lib/tomcats/$DEPLOYMENT_NAME"
